/*--OPTIONAL--*/

/*Add this line to USE A SPECIFIC DB*/
	--USE YOURDBNAME
/*--
	*This SQL COMMAND DISABLES ALL CONSTRAINTS FROM ALL TABLES IN THE CURRENT DATABASE
*/


/*--DECLARE THE SQL TEXT VARIABLE*/
DECLARE @sql NVARCHAR(MAX) = N'';

/*--STORE IN CTE ALL TABLES WITH CONSTRAINTS--*/
;WITH x AS 
(
  SELECT DISTINCT obj = 
      QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' 
    + QUOTENAME(OBJECT_NAME(parent_object_id)) 
  FROM sys.foreign_keys
)
/*--ADD ALL COLUMNS TO THE SQL TEXT--*/
SELECT @sql += N'ALTER TABLE ' + obj + ' NOCHECK CONSTRAINT ALL;' FROM x;
/*--QUERY EXECUTION--*/
EXEC(@sql)

/*--TESTING--*/
--PRINT @sql
--SELECT @sql

GO
